name: csharp-tests

on:
  push:
    branches:
      - main
    pull_request:

jobs:
  generate-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install npm tools
        run: npm install -g @stoplight/prism-cli@5.14.2 @openapitools/openapi-generator-cli@2.22.0

      - name: Install cucumber-json-formatter
        run: |
          curl -L https://github.com/cucumber/json-formatter/releases/download/v19.0.0/cucumber-json-formatter-linux-amd64 -o cucumber-json-formatter
          chmod +x cucumber-json-formatter
          sudo mv cucumber-json-formatter /usr/local/bin/

      - name: Install jd
        run: |
          curl -L https://github.com/josephburnett/jd/releases/download/v2.5.0/jd-amd64-linux -o jd
          chmod +x jd
          sudo mv jd /usr/local/bin/

      - name: Install shUnit2
        run: sudo apt install shunit2 -y

      - name: Test csharp codegen
        run: ./test_codegen.sh --filter testCSharpCodegen
        working-directory: tests
